CREATE TABLE IF NOT EXISTS profile (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL DEFAULT '',
	birth_date DATE NOT NULL DEFAULT CURRENT_DATE,
	photo TEXT NOT NULL DEFAULT '',
	login TEXT NOT NULL UNIQUE DEFAULT '',
	password TEXT NOT NULL DEFAULT '',
	email TEXT NOT NULL UNIQUE DEFAULT '',
	registration_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	role TEXT NOT NULL DEFAULT 'user'
);
