CREATE TABLE IF NOT EXISTS profile (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL DEFAULT '',
	birth_date DATE NOT NULL DEFAULT CURRENT_DATE,
	photo VARCHAR(100) NOT NULL DEFAULT '',
	login VARCHAR(100) NOT NULL UNIQUE DEFAULT '',
	password VARCHAR(255) NOT NULL DEFAULT '',
	email VARCHAR(100) NOT NULL UNIQUE DEFAULT '',
	registration_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
