CREATE TABLE IF NOT EXISTS crew ( 
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL DEFAULT '',
	birth_date DATE NOT NULL DEFAULT CURRENT_DATE,
	photo TEXT NOT NULL DEFAULT '',
	info TEXT NOT NULL DEFAULT '',
	country TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS profession (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS film (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL DEFAULT '',
	info TEXT NOT NULL DEFAULT '',
	poster TEXT NOT NULL DEFAULT '',
	release_date TEXT NOT NULL DEFAULT '2023',
	country TEXT NOT NULL DEFAULT '',
	mpaa TEXT NOT NULL DEFAULT '',
	fts TSVECTOR
);

CREATE INDEX IF NOT EXISTS film_fts ON film USING GIN (fts);

CREATE TABLE IF NOT EXISTS person_in_film (
	id_person SERIAL NOT NULL REFERENCES crew(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	id_film SERIAL NOT NULL REFERENCES film(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	id_profession SERIAL NOT NULL REFERENCES profession(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	character_name TEXT DEFAULT '',
	
	PRIMARY KEY(id_person, id_film, id_profession)
);

CREATE TABLE IF NOT EXISTS genre (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS films_genre (
	id_film SERIAL NOT NULL REFERENCES film(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	id_genre SERIAL NOT NULL REFERENCES genre(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	
	PRIMARY KEY(id_film, id_genre)
);

CREATE TABLE IF NOT EXISTS users_comment (
	id_user SERIAL NOT NULL,
	id_film SERIAL NOT NULL REFERENCES film(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	rating INTEGER NOT NULL DEFAULT '5'
		CONSTRAINT rating_is_positive CHECK (rating >= 0),
	
	PRIMARY KEY(id_user, id_film)
);

CREATE TABLE IF NOT EXISTS users_favorite_actor (
	id_user SERIAL NOT NULL,
	id_actor SERIAL NOT NULL REFERENCES crew(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,

	PRIMARY KEY(id_user, id_actor)
);

CREATE TABLE IF NOT EXISTS users_favorite_film (
	id_user SERIAL NOT NULL,
	id_film SERIAL NOT NULL REFERENCES film(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,

	PRIMARY KEY(id_user, id_film)
);

CREATE TABLE IF NOT EXISTS calendar (
	id SERIAL PRIMARY KEY REFERENCES film(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	release_year INTEGER NOT NULL DEFAULT DATE_PART('YEAR', CURRENT_DATE)
		CONSTRAINT release_year_constraint CHECK (release_year >=  DATE_PART('YEAR', CURRENT_DATE)),
	release_month INTEGER NOT NULL DEFAULT DATE_PART('MONTH', CURRENT_DATE)
		CONSTRAINT release_month_constraint CHECK (release_month >=  DATE_PART('MONTH', CURRENT_DATE)),
	release_day INTEGER NOT NULL DEFAULT DATE_PART('DAY', CURRENT_DATE)
		CONSTRAINT release_day_constraint CHECK (release_day >=  DATE_PART('DAY', CURRENT_DATE))
);
