// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Auth_Check_Request struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_Check_Request) Reset()         { *m = Auth_Check_Request{} }
func (m *Auth_Check_Request) String() string { return proto.CompactTextString(m) }
func (*Auth_Check_Request) ProtoMessage()    {}
func (*Auth_Check_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *Auth_Check_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_Check_Request.Unmarshal(m, b)
}
func (m *Auth_Check_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_Check_Request.Marshal(b, m, deterministic)
}
func (m *Auth_Check_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_Check_Request.Merge(m, src)
}
func (m *Auth_Check_Request) XXX_Size() int {
	return xxx_messageInfo_Auth_Check_Request.Size(m)
}
func (m *Auth_Check_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_Check_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_Check_Request proto.InternalMessageInfo

func (m *Auth_Check_Request) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type Auth_Check_Reply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_Check_Reply) Reset()         { *m = Auth_Check_Reply{} }
func (m *Auth_Check_Reply) String() string { return proto.CompactTextString(m) }
func (*Auth_Check_Reply) ProtoMessage()    {}
func (*Auth_Check_Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Auth_Check_Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_Check_Reply.Unmarshal(m, b)
}
func (m *Auth_Check_Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_Check_Reply.Marshal(b, m, deterministic)
}
func (m *Auth_Check_Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_Check_Reply.Merge(m, src)
}
func (m *Auth_Check_Reply) XXX_Size() int {
	return xxx_messageInfo_Auth_Check_Reply.Size(m)
}
func (m *Auth_Check_Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_Check_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_Check_Reply proto.InternalMessageInfo

func (m *Auth_Check_Reply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*Auth_Check_Request)(nil), "auth.Auth_Check_Request")
	proto.RegisterType((*Auth_Check_Reply)(nil), "auth.Auth_Check_Reply")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xd4, 0xb8, 0x84, 0x1c, 0x4b,
	0x4b, 0x32, 0xe2, 0x9d, 0x33, 0x52, 0x93, 0xb3, 0xe3, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0x04, 0xb8, 0x98, 0x8b, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c,
	0x25, 0x2d, 0x2e, 0x01, 0x14, 0x75, 0x05, 0x39, 0x95, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0x25, 0x89,
	0x25, 0xa5, 0xc5, 0x60, 0x85, 0x1c, 0x41, 0x50, 0x9e, 0x91, 0x37, 0x17, 0xbb, 0x7b, 0x51, 0x6a,
	0x6a, 0x49, 0x6a, 0x91, 0x90, 0x03, 0x17, 0x17, 0x42, 0x9b, 0x90, 0x84, 0x1e, 0xd8, 0x7e, 0x4c,
	0x0b, 0xa5, 0xc4, 0xb0, 0xc8, 0x14, 0xe4, 0x54, 0x2a, 0x31, 0x38, 0x31, 0x45, 0x31, 0x24, 0xb1,
	0x81, 0x5d, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xc3, 0x61, 0x43, 0xbf, 0x00, 0x00,
	0x00,
}
